// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: Products.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeId        int64                  `protobuf:"varint,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ReviewScore   float64                `protobuf:"fixed64,7,opt,name=review_score,json=reviewScore,proto3" json:"review_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_Products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_Products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_Products_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetReviewScore() float64 {
	if x != nil {
		return x.ReviewScore
	}
	return 0
}

type ProductId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductId) Reset() {
	*x = ProductId{}
	mi := &file_Products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductId) ProtoMessage() {}

func (x *ProductId) ProtoReflect() protoreflect.Message {
	mi := &file_Products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductId.ProtoReflect.Descriptor instead.
func (*ProductId) Descriptor() ([]byte, []int) {
	return file_Products_proto_rawDescGZIP(), []int{1}
}

func (x *ProductId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_Products_proto protoreflect.FileDescriptor

const file_Products_proto_rawDesc = "" +
	"\n" +
	"\x0eProducts.proto\x12\x0fProductsPackage\x1a\x1bgoogle/protobuf/empty.proto\"\xa1\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\atype_id\x18\x04 \x01(\x03R\x06typeId\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12!\n" +
	"\freview_score\x18\a \x01(\x01R\vreviewScore\"\x1b\n" +
	"\tProductId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xa2\x02\n" +
	"\x10ProductsContract\x12A\n" +
	"\rCreateProduct\x12\x18.ProductsPackage.Product\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\vReadProduct\x12\x1a.ProductsPackage.ProductId\x1a\x18.ProductsPackage.Product\x12A\n" +
	"\rUpdateProduct\x12\x18.ProductsPackage.Product\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\rDeleteProduct\x12\x1a.ProductsPackage.ProductId\x1a\x16.google.protobuf.EmptyB\x14Z\x12Products/contractsb\x06proto3"

var (
	file_Products_proto_rawDescOnce sync.Once
	file_Products_proto_rawDescData []byte
)

func file_Products_proto_rawDescGZIP() []byte {
	file_Products_proto_rawDescOnce.Do(func() {
		file_Products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Products_proto_rawDesc), len(file_Products_proto_rawDesc)))
	})
	return file_Products_proto_rawDescData
}

var file_Products_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Products_proto_goTypes = []any{
	(*Product)(nil),       // 0: ProductsPackage.Product
	(*ProductId)(nil),     // 1: ProductsPackage.ProductId
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_Products_proto_depIdxs = []int32{
	0, // 0: ProductsPackage.ProductsContract.CreateProduct:input_type -> ProductsPackage.Product
	1, // 1: ProductsPackage.ProductsContract.ReadProduct:input_type -> ProductsPackage.ProductId
	0, // 2: ProductsPackage.ProductsContract.UpdateProduct:input_type -> ProductsPackage.Product
	1, // 3: ProductsPackage.ProductsContract.DeleteProduct:input_type -> ProductsPackage.ProductId
	2, // 4: ProductsPackage.ProductsContract.CreateProduct:output_type -> google.protobuf.Empty
	0, // 5: ProductsPackage.ProductsContract.ReadProduct:output_type -> ProductsPackage.Product
	2, // 6: ProductsPackage.ProductsContract.UpdateProduct:output_type -> google.protobuf.Empty
	2, // 7: ProductsPackage.ProductsContract.DeleteProduct:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Products_proto_init() }
func file_Products_proto_init() {
	if File_Products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Products_proto_rawDesc), len(file_Products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Products_proto_goTypes,
		DependencyIndexes: file_Products_proto_depIdxs,
		MessageInfos:      file_Products_proto_msgTypes,
	}.Build()
	File_Products_proto = out.File
	file_Products_proto_goTypes = nil
	file_Products_proto_depIdxs = nil
}
